# Generated by Django 3.2 on 2021-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('title',), 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AddField(
            model_name='post',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس مقدمه پست'),
        ),
    ]
