# Generated by Django 3.2 on 2021-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210528_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
