version: '3'
volumes:
  BlogDbData:
services:
  database:
    image: "postgres:10-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: usr_blog
      POSTGRES_PASSWORD: 123456
      PGPASSWORD: 123456
      POSTGRES_DB: maktab_blog
      PGDATA: /db_data
    volumes:
      - BlogDbData:/db_data